name: 'Verify an NPM release'
description: 'Fetches a package from NPM and does some basic smoke tests'

inputs:
  npm-package:
    description: 'NPM Package'
    required: true
    default: '@google/gemini-cli@latest'
  expected-version:
    description: 'Expected version'
    required: true
  ref:
    description: 'The branch, tag, or SHA to release from.'
    required: false
    type: 'string'
    default: 'main'

runs:
  using: 'composite'
  steps:
    - name: 'Checkout'
      uses: 'actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955' # ratchet:actions/checkout@v4
      with:
        path: 'verify'
        ref: '${{ github.event.inputs.ref }}'
        fetch-depth: 0

    - name: 'Install from NPM'
      uses: 'nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08' # ratchet:nick-fields/retry@v3
      with:
        timeout_seconds: 900
        retry_wait_seconds: 30
        max_attempts: 10
        command: 'cd ./verify && pkg="${{ inputs.npm-package }}" && npm install --prefer-online --no-cache -g "$pkg"'

    - name: '🔬 Run integration tests against NPM release'
      if: "inputs.dry-run == 'false' && inputs.force-skip-tests == 'false'"
      working-directory: '${{ inputs.working-directory }}'
      env:
        TEST_INSTALLED_GEMINI: 'true'
      shell: 'bash'
      run: 'npm run test:integration:sandbox:none'
